// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCL1pykBhWWysFnAtcMLm1Ii-gmx53wA',
    appId: '1:300565820012:web:30198f862f36d9304dde49',
    messagingSenderId: '300565820012',
    projectId: 'simpanin-id',
    authDomain: 'simpanin-id.firebaseapp.com',
    storageBucket: 'simpanin-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZwLYKwUA13zQ6AxzoomxIdKDt2wnABU',
    appId: '1:300565820012:android:e19c6b826af21a1a4dde49',
    messagingSenderId: '300565820012',
    projectId: 'simpanin-id',
    storageBucket: 'simpanin-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfrvpEsva0x-8Cl7R5ktc6F4gGTkss28',
    appId: '1:300565820012:ios:0b632d46f45a7ac14dde49',
    messagingSenderId: '300565820012',
    projectId: 'simpanin-id',
    storageBucket: 'simpanin-id.appspot.com',
    iosBundleId: 'com.example.simpanin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRfrvpEsva0x-8Cl7R5ktc6F4gGTkss28',
    appId: '1:300565820012:ios:146f5dbaac7982ae4dde49',
    messagingSenderId: '300565820012',
    projectId: 'simpanin-id',
    storageBucket: 'simpanin-id.appspot.com',
    iosBundleId: 'com.example.simpanin.RunnerTests',
  );
}
